// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Corvus.ContentHandling.Json.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Serializing content")]
    [NUnit.Framework.CategoryAttribute("setupContainer")]
    public partial class SerializingContentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SerializingContent.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Serializing content", "\tIn order to support polymorphic content type serialization\r\n\tAs a developer\r\n\tI " +
                    "want to be able to serialize polymorphic types to a JSON format", ProgrammingLanguage.CSharp, new string[] {
                        "setupContainer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common interface")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonInterface()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common interface", null, ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table26.AddRow(new string[] {
                        "Hello"});
#line 8
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithinterface\'", ((string)(null)), table26, "Given ");
#line 11
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithinterface\", \"someValue\": \"Hello\" }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common interface with a nul" +
            "l polymorphic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonInterfaceWithANullPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common interface with a nul" +
                    "l polymorphic child object", null, new string[] {
                        "useChildObjects"});
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table27.AddRow(new string[] {
                        "Hello",
                        "null"});
#line 16
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithinterfaceandchild\'", ((string)(null)), table27, "Given ");
#line 19
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithinterfaceandchild\", \"someValue\": \"Hello\", \"child\": nul" +
                    "l }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common interface with a pol" +
            "ymorphic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonInterfaceWithAPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common interface with a pol" +
                    "ymorphic child object", null, new string[] {
                        "useChildObjects"});
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table28.AddRow(new string[] {
                        "Dolly"});
#line 24
 testRunner.Given("I have an instance of a content object called \'child\' with content type \'applicat" +
                    "ion/vnd.corvus.somecontentwithinterface\'", ((string)(null)), table28, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table29.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 27
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithinterfaceandchild\'", ((string)(null)), table29, "And ");
#line 30
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithinterfaceandchild\", \"someValue\": \"Hello\", \"child\": { \"" +
                    "contentType\": \"application/vnd.corvus.somecontentwithinterface\", \"someValue\": \"D" +
                    "olly\" } }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common interface with a POC" +
            " child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonInterfaceWithAPOCChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common interface with a POC" +
                    " child object", null, new string[] {
                        "useChildObjects"});
#line 34
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table30.AddRow(new string[] {
                        "Dolly"});
#line 35
 testRunner.Given("I have an instance of a poc object called \'child\'", ((string)(null)), table30, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table31.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 38
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithinterfaceandpocchild\'", ((string)(null)), table31, "And ");
#line 41
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithinterfaceandpocchild\", \"someValue\": \"Hello\", \"child\": " +
                    "{ \"someValue\": \"Dolly\" } }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common abstract base")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonAbstractBase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common abstract base", null, ((string[])(null)));
#line 46
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table32.AddRow(new string[] {
                        "Hello"});
#line 47
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithabstractbase\'", ((string)(null)), table32, "Given ");
#line 50
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithabstractbase\", \"someValue\": \"Hello\" }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common abstract base with a" +
            " null polymorphic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonAbstractBaseWithANullPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common abstract base with a" +
                    " null polymorphic child object", null, new string[] {
                        "useChildObjects"});
#line 54
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table33.AddRow(new string[] {
                        "Hello",
                        "null"});
#line 55
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithabstractbaseandchild\'", ((string)(null)), table33, "Given ");
#line 58
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithabstractbaseandchild\", \"someValue\": \"Hello\", \"child\": " +
                    "null }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common abstract base with a" +
            " polymorphic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonAbstractBaseWithAPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common abstract base with a" +
                    " polymorphic child object", null, new string[] {
                        "useChildObjects"});
#line 62
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table34.AddRow(new string[] {
                        "Dolly"});
#line 63
 testRunner.Given("I have an instance of a content object called \'child\' with content type \'applicat" +
                    "ion/vnd.corvus.somecontentwithabstractbase\'", ((string)(null)), table34, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table35.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 66
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithabstractbaseandchild\'", ((string)(null)), table35, "And ");
#line 69
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.Then(@"the value called 'result' should be a json object '{ ""contentType"": ""application/vnd.corvus.somecontentwithabstractbaseandchild"", ""someValue"": ""Hello"", ""child"": { ""contentType"": ""application/vnd.corvus.somecontentwithabstractbase"", ""someValue"": ""Dolly"" } }'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common abstract base with a" +
            " POC child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonAbstractBaseWithAPOCChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common abstract base with a" +
                    " POC child object", null, new string[] {
                        "useChildObjects"});
#line 73
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table36.AddRow(new string[] {
                        "Dolly"});
#line 74
 testRunner.Given("I have an instance of a poc object called \'child\'", ((string)(null)), table36, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table37.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 77
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithabstractbaseandpocchild\'", ((string)(null)), table37, "And ");
#line 80
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithabstractbaseandpocchild\", \"someValue\": \"Hello\", \"child" +
                    "\": { \"someValue\": \"Dolly\" } }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common base")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonBase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common base", null, ((string[])(null)));
#line 85
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table38.AddRow(new string[] {
                        "Hello"});
#line 86
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithbase\'", ((string)(null)), table38, "Given ");
#line 89
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithbase\", \"someValue\": \"Hello\" }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common base with a null pol" +
            "ymorphic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonBaseWithANullPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common base with a null pol" +
                    "ymorphic child object", null, new string[] {
                        "useChildObjects"});
#line 93
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table39.AddRow(new string[] {
                        "Hello",
                        "null"});
#line 94
 testRunner.Given("I have an instance of a content object called \'item\' with content type \'applicati" +
                    "on/vnd.corvus.somecontentwithbaseandchild\'", ((string)(null)), table39, "Given ");
#line 97
 testRunner.When("I serialize the content object called \'item\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithbaseandchild\", \"someValue\": \"Hello\", \"child\": null }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common base with a polymorp" +
            "hic child object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonBaseWithAPolymorphicChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common base with a polymorp" +
                    "hic child object", null, new string[] {
                        "useChildObjects"});
#line 101
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table40.AddRow(new string[] {
                        "Dolly"});
#line 102
 testRunner.Given("I have an instance of a content object called \'child\' with content type \'applicat" +
                    "ion/vnd.corvus.somecontentwithbase\'", ((string)(null)), table40, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table41.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 105
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithbaseandchild\'", ((string)(null)), table41, "And ");
#line 108
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithbaseandchild\", \"someValue\": \"Hello\", \"child\": { \"conte" +
                    "ntType\": \"application/vnd.corvus.somecontentwithbase\", \"someValue\": \"Dolly\" } }\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a polymorphic content object implementing a common base with a POC chil" +
            "d object")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPolymorphicContentObjectImplementingACommonBaseWithAPOCChildObject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a polymorphic content object implementing a common base with a POC chil" +
                    "d object", null, new string[] {
                        "useChildObjects"});
#line 112
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue"});
            table42.AddRow(new string[] {
                        "Dolly"});
#line 113
 testRunner.Given("I have an instance of a poc object called \'child\'", ((string)(null)), table42, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "Child"});
            table43.AddRow(new string[] {
                        "Hello",
                        "{child}"});
#line 116
 testRunner.And("I have an instance of a content object called \'parent\' with content type \'applica" +
                    "tion/vnd.corvus.somecontentwithbaseandpocchild\'", ((string)(null)), table43, "And ");
#line 119
 testRunner.When("I serialize the content object called \'parent\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
 testRunner.Then("the value called \'result\' should be a json object \'{ \"contentType\": \"application/" +
                    "vnd.corvus.somecontentwithbaseandpocchild\", \"someValue\": \"Hello\", \"child\": { \"so" +
                    "meValue\": \"Dolly\" } }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize a poc object with an enum")]
        [NUnit.Framework.CategoryAttribute("useChildObjects")]
        public virtual void SerializeAPocObjectWithAnEnum()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize a poc object with an enum", null, new string[] {
                        "useChildObjects"});
#line 123
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "SomeValue",
                        "SomeEnum"});
            table44.AddRow(new string[] {
                        "Hello",
                        "ThirdTimeIsTheCharm"});
#line 124
 testRunner.Given("I have an instance of a poc object with enum called \'subject\'", ((string)(null)), table44, "Given ");
#line 127
 testRunner.When("I serialize the content object called \'subject\' as \'result\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.Then("the value called \'result\' should be a json object \'{ \"someValue\": \"Hello\", \"someE" +
                    "num\": \"thirdTimeIsTheCharm\" }\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
